version: '3'

services:
  lazyfolks:
    container_name: lazyfolks
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - DEBUG=0
    image: onexspace/lazyfolks:prod
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - ./lazyfolks:/lazyfolks